// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW9hwLYytwNDpjGoqJ6_JXmlG1gJhFnt0',
    appId: '1:943372900824:web:b93e4fffd475806019faad',
    messagingSenderId: '943372900824',
    projectId: 'routines-fccbb',
    authDomain: 'routines-fccbb.firebaseapp.com',
    storageBucket: 'routines-fccbb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2ont-DsJY1dZ_iIjt3tGn9yv82dQBd0A',
    appId: '1:943372900824:android:a6a620fcdf9e7f0019faad',
    messagingSenderId: '943372900824',
    projectId: 'routines-fccbb',
    storageBucket: 'routines-fccbb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9lMlF0JP20B9sYHFqIoFzNzFboKozoVc',
    appId: '1:943372900824:ios:66ec3b98877eb1db19faad',
    messagingSenderId: '943372900824',
    projectId: 'routines-fccbb',
    storageBucket: 'routines-fccbb.appspot.com',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9lMlF0JP20B9sYHFqIoFzNzFboKozoVc',
    appId: '1:943372900824:ios:b1e24db33497a6ef19faad',
    messagingSenderId: '943372900824',
    projectId: 'routines-fccbb',
    storageBucket: 'routines-fccbb.appspot.com',
    iosBundleId: 'com.example.assignment.RunnerTests',
  );
}
